# Page settings
baseurl = "https://ly.atom.im"
languageCode = "en-us"
title = "Call for papers"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

disableHugoGeneratorInject = true

[blackfriday]
fractions = false
hrefTargetBlank = true

# Meta
[params]
description = "Selected call for papers from top computer architecture & system conferences."
keywords = "conference, computer science and technology, non-volatile memory, NVM, file system, operating system"
author = "Hu Wan"

# Introduction section
[params.intro]
enable = true
title = "Call for Papers!"
intro = "Important dates of selected conferences in computer architecture & system fields."
notes = "**Note**: Deadlines are shown in timezone from conference website. Timelines and countdowns are shown in Asia/Hong_Kong timezone. Deadlines for conferences with * have not yet been announced."

# Links
[params.info]
enable = true
info = "**Link**: [Chinese Computing Federation (CCF) Ranking List](https://ccf.atom.im). Report bug at [here](https://github.com/atom-im/cfp/issues)."

# Footer section
[params.footer]
copyright = "Theme designed by [dblp](https://dblp.uni-trier.de/), customized by [atom.im](https://atom.im)."

# Timeline section
[params.timeline]
enable = true

# Highlight section
[params.highlight]
enable = true
title = "Featured Call"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# Upcoming section
[params.upcoming]
enable = true
title = "Upcoming Calls"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Countdown"

# current section
[params.current]
enable = true
title = "Inactive Calls"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event starts in"

# past section
[params.past]
enable = true
title = "Past Calls"
name = "Name"
rank="Rank"
when = "When"
absddl = "Abstract Deadline"
submddl = "Submission Deadline"
notidue = "Notification Due"
countdown = "Event Status"

# Important dates of conferences
# NOTE 1: enable (0: hide, 1: show, 2: highlight)
# NOTE 2: date format: 2006-01-02 15:04:05 -07:00
#         must two digits for each field
[[params.cfp.list]]
enable = 2
name = "ASPLOS"
rank = "A"
site = "https://asplos-conference.org/"
open = "2022-02-28"
close = "2022-03-04 23:59:59 -07:00"
absddl = "2021-08-06 14:59:59 -07:00"
submddl = "2021-08-13 14:59:59 -07:00"
notidue = "2021-11-15"

[[params.cfp.list]]
enable = 1
name = "FAST"
rank = "A"
site = "https://www.usenix.org/conference/fast22/call-for-papers"
open = "2022-02-21"
close = "2022-02-24 23:59:59"
absddl = "N/A"
submddl = "2021-09-23 23:59:59 -07:00"
notidue = "2021-12-10"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://www.dac.com/DAC-2022"
open = "2022-12-05"
close = "2022-12-09 23:59:59"
absddl = "2021-11-15 23:59:59 +15:00"
submddl = "2021-11-22 23:59:59 +15:00"
notidue = "2021-12-05"

[[params.cfp.list]]
enable = 1
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc22"
open = "2022-06-11"
close = "2022-06-13 23:59:59"
absddl = "2022-01-06 23:59:00 -8:00"
submddl = "2022-01-13 23:59:00 -8:00"
notidue = "2022-04-29"

[[params.cfp.list]]
enable = 1
name = "CCS"
rank = "A"
site = "https://www.sigsac.org/ccs/CCS2021/"
open = "2021-11-15"
close = "2021-11-19 23:59:59"
absddl = "2021-01-20 23:59:59 +20:00"
submddl = "2021-01-20 23:59:59 +20:00"
notidue = "2021-05-05"

[[params.cfp.list]]
enable = 1
name = "EUROCRYP"
rank = "A"
site = "https://eurocrypt.iacr.org/2022/"
open = "2022-05-30"
close = "2022-06-03 23:59:59"
absddl = "2021-10-01 23:59:59 +06:00"
submddl = "2021-10-01 23:59:59 +06:00"
notidue = "2022-02-01"

[[params.cfp.list]]
enable = 1
name = "S&P"
rank = "A"
site = "http://www.ieee-security.org/TC/EuroSP2021"
open = "2022-06-06"
close = "2022-06-10 23:59:59"
absddl = "2021-09-22"
submddl = "2021-09-22"
notidue = "2021-01-18"

[[params.cfp.list]]
enable = 1
name = "USENIX Security"
rank = "A"
site = "https://www.usenix.org/conference/usenixsecurity22"
open = "2022-08-10"
close = "2022-08-22 23:59:59"
absddl = "2021-06-08"
submddl = "2021-06-08"
notidue = "2021-09-03"


[[params.cfp.list]]
enable = 1
name = "ATC"
rank = "A"
site = "https://www.usenix.org/conference/atc21/call-for-papers"
open = "2021-07-14"
close = "2021-07-16 23:59:59"
absddl = "N/A"
submddl = "2021-01-12 23:59:59 +00:00"
notidue = "2021-04-26"

[[params.cfp.list]]
enable = 1
name = "PPoPP"
rank = "A"
site = "https://ppopp21.sigplan.org"
open = "2021-02-27"
close = "2021-03-03 23:59:59"
absddl = "2020-08-06"
submddl = "2020-08-13"
notidue = "2020-11-16"

[[params.cfp.list]]
enable = 0
name = "SPAA"
rank = "B"
site = "http://spaa.acm.org/"
open = "2021-06-06"
close = "2021-06-08 23:59:59"
absddl = "2021-02-08"
submddl = "2021-02-11"
notidue = "2021-04-18"

[[params.cfp.list]]
enable = 0
name = "PODC"
rank = "B"
site = "https://www.podc.org/"
open = "2021-07-26"
close = "2021-07-30 23:59:59"
absddl = "2021-02-11"
submddl = "2021-02-15"
notidue = "2021-04-30"

[[params.cfp.list]]
enable = 1
name = "DAC"
rank = "A"
site = "https://dac.com"
open = "2021-07-11"
close = "2021-07-15 23:59:59"
absddl = "2020-11-16"
submddl = "2020-11-23"
notidue = "2021-02-24"

[[params.cfp.list]]
enable = 1
name = "DATE"
rank = "B"
site = "https://www.date-conference.com/"
open = "2021-02-01"
close = "2021-02-05 23:59:59"
absddl = "2020-09-14 23:59:59 +02:00"
submddl = "2020-09-21 23:59:59 +02:00"
notidue = "2020-11-13"

[[params.cfp.list]]
enable = 1
name = "EuroSys"
rank = "B"
site = "https://2021.eurosys.org/"
open = "2021-04-26"
close = "2021-04-29 23:59:59"
absddl = "2020-10-01"
submddl = "2020-10-09"
notidue = "2021-01-20"

[[params.cfp.list]]
enable = 0
name = "HPDC"
rank = "B"
site = "http://www.hpdc.org/2021/"
open = "2021-06-21"
close = "2021-06-25 23:59:59"
absddl = "2021-01-17"
submddl = "2021-01-24"
notidue = "2021-03-28"

[[params.cfp.list]]
enable = 1
name = "ICCD"
rank = "B"
site = "http://www.iccd-conf.com"
open = "2021-10-24"
close = "2021-10-27 23:59:59"
absddl = "2021-05-28 23:59:59 -12:00"
submddl = "2021-06-04 23:59:59 -12:00"
notidue = "2021-08-20"

[[params.cfp.list]]
enable = 1
name = "ICCAD"
rank = "B"
site = "http://www.iccad-conf.com"
open = "2019-07-02"
close = "2019-07-03 23:59:59"
absddl = "N/A"
submddl = "2020-01-31"
notidue = "2020-03-31"

[[params.cfp.list]]
enable = 1
name = "HiPEAC"
rank = "B"
site = "http://hipeac.net/conference"
open = "2021-01-18"
close = "2021-01-20 23:59:59"
absddl = "N/A"
submddl = "2020-11-15"
notidue = "2020-11-15"

[[params.cfp.list]]
enable = 1
name = "SIGMETRICS"
rank = "B"
site = "https://www.sigmetrics.org/sigmetrics2021"
open = "2021-06-14"
close = "2021-06-18 23:59:59"
absddl = "2020-10-16"
submddl = "2020-10-23"
notidue = "2020-12-15"

[[params.cfp.list]]
enable = 0
name = "ICPP"
rank = "B"
site = "http://www.icpp-conf.org"
open = "2021-08-09"
close = "2021-08-12 23:59:59 +09:00"
absddl = "2021-04-10"
submddl = "2021-04-16"
notidue = "2021-06-11"

[[params.cfp.list]]
enable = 0
name = "ICS"
rank = "B"
site = "https://ics21.github.io/"
open = "2021-06-14"
close = "2021-06-17 23:59:59"
absddl = "2021-01-28"
submddl = "2021-02-04"
notidue = "2021-03-31"

[[params.cfp.list]]
enable = 0
name = "IPDPS"
rank = "B"
site = "http://www.ipdps.org/"
open = "2021-05-17"
close = "2021-05-21 23:59:59"
absddl = "2020-10-12 23:59:59 -12:00"
submddl = "2020-10-19 23:59:59 -12:00"
notidue = "2020-12-09"

[[params.cfp.list]]
enable = 1
name = "MSST"
rank = "B"
site = "http://storageconference.us/"
open = "2020-10-26"
close = "2020-10-30 23:59:59"
absddl = "N/A"
submddl = "2020-01-07"
notidue = "2020-02-15"

[[params.cfp.list]]
enable = 0
name = "PACT"
rank = "B"
site = "http://ssd.sscc.ru/conference/pact2021/"
open = "2021-10-03"
close = "2021-10-07 23:59:59"
absddl = "N/A"
submddl = "2021-03-31"
notidue = "2021-04-15"

[[params.cfp.list]]
enable = 0
name = "OOPSLA"
rank = "A"
site = "https://2021.splashcon.org/"
open = "2021-10-17"
close = "2021-10-22 23:59:59"
absddl = "N/A"
submddl = "2021-04-16"
notidue = "2021-07-02"

[[params.cfp.list]]
enable = 0
name = "ICSE"
rank = "A"
site = "https://conf.researchr.org/home/icse-2021"
open = "2021-05-25"
close = "2021-05-28 23:59:59"
absddl = "N/A"
submddl = "2020-08-28 23:59:59 -12:00"
notidue = "2020-12-17"

[[params.cfp.list]]
enable = 1
name = "OSDI"
rank = "A"
site = "https://www.usenix.org/conference/osdi21/"
open = "2021-07-14"
close = "2021-07-16 23:59:59 -07:00"
absddl = "2020-12-03 15:00:00 -07:00"
submddl = "2020-12-10 15:00:00 -07:00"
notidue = "2021-03-16"

[[params.cfp.list]]
enable = 0
name = "PLDI"
rank = "A"
site = "http://pldi21.sigplan.org"
open = "2021-06-20"
close = "2021-06-25 23:59:59"
absddl = "N/A"
submddl = "2020-11-20"
notidue = "2021-02-25"

[[params.cfp.list]]
enable = 0
name = "POPL"
rank = "A"
site = "https://popl22.sigplan.org/"
open = "2022-01-16"
close = "2022-01-21 23:59:59"
absddl = "N/A"
submddl = "2021-07-08 23:59:59 -12:00"
notidue = "2021-10-01"

[[params.cfp.list]]
enable = 1
name = "SOSP"
rank = "A"
site = "https://sosp2021.mpi-sws.org/cfs.html"
open = "2021-10-25"
close = "2021-10-28 23:59:59"
absddl = "2021-04-30 02:59:59 -07:00"
submddl = "2021-05-07 02:59:59 -07:00"
notidue = "2021-08-09"

[[params.cfp.list]]
enable = 1
name = "HotOS"
rank = "B"
site = "https://www.sigops.org/2018/hotos2019/"
open = "2019-05-12"
close = "2019-05-15 23:59:59"
absddl = "N/A"
submddl = "2019-01-17"
notidue = "2019-03-11"

[[params.cfp.list]]
enable = 0
name = "SIGMOD"
rank = "A"
site = "https://2021.sigmod.org/"
open = "2021-06-20"
close = "2021-06-25 23:59:59"
absddl = "N/A"
submddl = "2020-09-22"
notidue = "2020-11-30"

[[params.cfp.list]]
enable = 0
name = "VLDB"
rank = "A"
site = "http://vldb.org/2021/"
open = "2021-08-16"
close = "2021-08-20 23:59:59"
absddl = "2021-02-20"
submddl = "2021-03-01"
notidue = "2021-04-15"

[[params.cfp.list]]
enable = 0
name = "ICDE-1"
rank = "A"
site = "https://icde2021.gr/"
open = "2021-04-19"
close = "2021-04-23 23:59:59"
absddl = "2020-06-10"
submddl = "2020-06-17"
notidue = "2020-10-02"

[[params.cfp.list]]
enable = 0
name = "ICDE"
rank = "A"
site = "https://icde2021.gr/"
open = "2021-04-19"
close = "2021-04-23 23:59:59"
absddl = "2020-10-07 23:59:59 -12:00"
submddl = "2020-10-14 23:59:59 -12:00"
notidue = "2021-02-09"

[[params.cfp.list]]
enable = 0
name = "CIDR"
rank = "A"
site = "http://cidrdb.org/cidr2020/"
open = "2020-01-12"
close = "2020-01-15 23:59:59"
absddl = "N/A"
submddl = "2019-08-23 23:59:59 -07:00"
notidue = "2019-10-14"

[[params.cfp.list]]
enable = 0
name = "EMSOFT"
rank = "B"
site = "http://www.esweek.org"
open = "2021-10-10"
close = "2021-10-15 23:59:59"
absddl = "2021-04-02"
submddl = "2021-04-09"
notidue = "2021-07-05"

[[params.cfp.list]]
enable = 1
name = "CODES+ISSS"
rank = "B"
site = "http://www.esweek.org"
open = "2021-10-10"
close = "2021-10-15 23:59:59"
absddl = "2021-04-02"
submddl = "2021-04-09"
notidue = "2021-07-05"

[[params.cfp.list]]
enable = 0
name = "NVMSA"
rank = ""
site = "https://nvmsa2021.github.io/index"
open = "2021-08-18"
close = "2021-08-20 23:59:59"
absddl = "2021-05-14 23:59:59 -12:00"
submddl = "2021-05-21 23:59:59 -12:00"
notidue = "2021-06-25"

[[params.cfp.list]]
enable = 1
name = "HotStorage"
rank = ""
site = "https://www.hotstorage.org/2021/"
open = "2021-07-27"
close = "2021-07-28 23:59:59"
absddl = "N/A"
submddl = "2021-04-30"
notidue = "2021-06-08"

[[params.cfp.list]]
enable = 0
name = "SysML"
rank = ""
site = "https://systemsandml.org"
open = "2021-04-04"
close = "2021-04-07 23:59:59"
absddl = "N/A"
submddl = "2020-09-22 16:59:59 -07:00"
notidue = "2021-01-18"

[[params.cfp.list]]
enable = 1
name = "Mobicom"
rank = "A"
site = "https://sigmobile.org/mobicom/2021/"
open = "2021-10-25"
close = "2021-10-29 23:59:59"
absddl = "2021-03-19"
submddl = "2021-03-26"
notidue = "2021-06-11"

[[params.cfp.list]]
enable = 1
name = "Mobihoc"
rank = "B"
site = "https://www.sigmobile.org/mobihoc/2021/"
open = "2021-07-26"
close = "2021-08-01 23:59:59"
absddl = "2020-12-12"
submddl = "2020-12-19"
notidue = "2021-05-02"

[[params.cfp.list]]
enable = 1
name = "Ubicomp"
rank = "B"
site = "http://ubicomp.org/ubicomp2021"
open = "2021-09-21"
close = "2021-09-26 23:59:59"
absddl = "N/A"
submddl = "2021-05-15"
notidue = "2021-07-15"

[[params.cfp.list]]
enable = 1
name = "HotMobile"
rank = "B"
site = "https://www.hotmobile.org/2021"
open = "2021-02-24"
close = "2021-02-26 23:59:59"
absddl = "2020-10-30"
submddl = "2020-11-06"
notidue = "2020-12-23"
